name: upes_parikshamitr_teacher_frontend
description: "ParikshaMitr Teacher App."
publish_to: "none"
version: 1.0.4+11

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: 1.0.1
  intl: 0.19.0
  shared_preferences: 2.2.2
  http: 1.2.0
  flutter_secure_storage: 9.0.0
  url_launcher: 6.2.6
  path_provider: 2.0.2
  open_file: 3.3.2
  flutter_pdfview: 1.3.2
  jsqr: any
  universal_html: any
  mobile_scanner: 4.0.1
  change_app_package_name: 1.1.0
  in_app_update: 4.2.2
  cupertino_icons: 1.0.2
  flutter_svg: 2.0.5
  carousel_slider: 4.0.0
  fluttertoast: 8.2.4
  collection: 1.18.0
  flutter_overlay_loader: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true

  assets:
    - android/assets/signinpage.svg
    - android/assets/examsummary.svg
    - android/assets/carousel1.svg
    - android/assets/carousel2.svg
    - android/assets/carousel3.svg
    - android/assets/ufm.svg
    - android/assets/controller.svg
    - android/assets/supplementary.svg
    - android/assets/doubt.svg
    - android/assets/leaveduty.svg
    - android/assets/qr.svg
    - android/assets/msg.svg
    - android/assets/call.svg
    - android/assets/refresh.svg
    - android/assets/sheetsubmit.svg
    - android/assets/seatingplan.svg
    - android/assets/attendancereport.svg
    - android/assets/studentlookup.svg
    - assets/upes_logo.svg
    - assets/upes_logo.png
    - assets/home_art.png
    - assets/Examination Guidelines for Control Room Supervisors (CRS).pdf
    - assets/Examination Guidelines for Flying Squad.pdf
    - assets/Examination Guidelines for Invigilators.pdf
    - assets/Answer Sheet Submission Guidelines.pdf
    - assets/evaluation.svg
    - assets/help.svg
    - assets/missing_sheet.svg
    - assets/start_exam.svg
    - assets/student_search.svg
    - assets/view_duty.svg
    - assets/profile.svg
    - assets/avatar.png

flutter_native_splash:
  color: "ffffff"
  image: assets/upes.jpeg
  android: true
  ios: true